/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'principal' : IDL.Principal,
  'puzzleType' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'timeTaken' : IDL.Int,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'principal' : IDL.Principal,
    'puzzleType' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'timeTaken' : IDL.Int,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };